<a href="https://colab.research.google.com/github/uneconomicalfairy14/javactrun/blob/master/ml/ml3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://raw.githubusercontent.com/codebasics/py/master/ML/4_save_model/homeprices.csv

--2022-06-12 16:11:23--  https://raw.githubusercontent.com/codebasics/py/master/ML/4_save_model/homeprices.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 71 [text/plain]
Saving to: ‘homeprices.csv’

homeprices.csv      100%[===================>]      71  --.-KB/s    in 0s      

2022-06-12 16:11:23 (4.25 MB/s) - ‘homeprices.csv’ saved [71/71]



In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [5]:
model.coef_

array([135.78767123])

In [6]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [7]:
import pickle

In [8]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [9]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [10]:
mp.coef_

array([135.78767123])

In [11]:
mp.intercept_

180616.43835616432

In [12]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [14]:
import joblib

In [15]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [16]:
mj = joblib.load('model_joblib')

In [17]:
mj.coef_

array([135.78767123])

In [18]:
mj.intercept_

180616.43835616432

In [19]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])